import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";

const cario = Cairo({
  subsets: ["latin"],
  variable: "--font-geist-sans",
  weight: ["300", "400", "500", "600", "700"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={`${cario.className}  antialiased`} //coment
      >
        {children}
      </body>
    </html>
  );
}
